### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by kauandefarias** [bluesky-social/atproto-website#18]
I'm not sure if that's the right place to suggest ideas, but I was wondering how can I help with the translation of the website to Brazilian Portuguese, since I'm a native on the language. Do you, developers, ever considered placing that option? That'd make users from other countries to understand better all the documentation written and help clarify things up more easily. Let me know if I can do so, and how! It'd be a pleasure.

**Comment by myConsciousness** [comment]
@kauandefarias ,

It's not practical to manually create translations for content. If we were to try to translate the content, the following problems would arise.

- Who will maintain it?
- Is it possible to translate all content?
- Can it be kept up-to-date? 

Since the documentation is even more prone to maintenance delays, it's better that we focus our efforts in this repository on maintaining the original English documentation. Besides, automatic translation is so sophisticated these days that we don't see the benefit of going to the trouble of creating translated content.

However, I think it's a good idea if you publish a website with translated contents of this repository as your personal project :)

**Comment by kauandefarias** [comment]
I understand! Thanks for the reply.
